//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DynamicQuery.Entity.Documentation
{
    public partial class Database : DynamicQueryDatabase
    {
    	public Database() : base()
    	{
        	// Tablak, mezok es kapcsolatok
        	
        	this.Tables.Add(new DynamicQueryTable("afakod")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "ÁFA kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "megnevezés", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "enev", Description = "megnevezés egyszerűsített számlán", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "afakulcs", Description = "ÁFA kulcs", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "safakulcs", Description = "ÁFA kulcs szövegesen", ColumnType = "string", Length = 3  },
                                	new DynamicQueryTableColumn(){ Name = "afatarolo", Description = "ÁFA tároló jele", ColumnType = "string", Length = 1  },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "törölve", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "cikktorzs", Description = "cikktörzsben használható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "listak", Description = "listákban használható", ColumnType  = "bool" },
                              },
            		Associations = new List<DynamicQueryTableAssociation>()
            					   {
                                    	new DynamicQueryTableAssociation() { Name = "FK_bevet_afakod", ForeignKeyColumn = "afakod", ForeignKeyTable = "bevet", PrimaryKeyColumn = "kod", PrimaryKeyTable = "afakod" },
                                    	new DynamicQueryTableAssociation() { Name = "FK_cikk_afakod", ForeignKeyColumn = "afakod", ForeignKeyTable = "cikk", PrimaryKeyColumn = "kod", PrimaryKeyTable = "afakod" },
                                   }			
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("agyujt")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "agyujtaz", Description = "adatgyűjtés azonosító", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "megnevezes", Description = "megnevezés", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "kuldes", Description = "küldés típus kód", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "ftpcim", Description = "FTP cím ahova küldjük", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "ftpuser", Description = "FTP user name", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "ftppassword", Description = "FTP password", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "gyakorisag", Description = "küldés gyakoriságának kódja", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "out_tipus", Description = "output fájl típus kód", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "etalonfajl", Description = "-", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "filenevmask", Description = "Fájl név felépétés maszk", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "engparam", Description = "Adatgyüjtés engedély paraméter azonosító (PARAM tábla)", ColumnType = "string", Length = 20  },
                                	new DynamicQueryTableColumn(){ Name = "sorszam_param", Description = "Adatgyűjtés sorszám paraméter azonosító (PARAM tábla)", ColumnType = "string", Length = 30  },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("arazo")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "cikkszam", Description = "Cikkszám", ColumnType = "string", Length = 13  },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "Cikk neve", ColumnType = "string", Length = 40  },
                                	new DynamicQueryTableColumn(){ Name = "kisz", Description = "Cikk kiszerelése", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "fogyar", Description = "Jelenlegi fogy.ár", ColumnType  = "decimal", Length = 18, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "ujar", Description = "Új fogy.ár", ColumnType  = "decimal", Length = 18, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "polc", Description = "Polc", ColumnType = "string", Length = 20  },
                                	new DynamicQueryTableColumn(){ Name = "rekesz", Description = "Rekesz azonosító", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "nyomtatva", Description = "Nyomtatva", ColumnType  = "bool" },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("bank")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "Bank neve", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "bankszla", Description = "Bankszámlaszám", ColumnType = "string", Length = 24  },
                                	new DynamicQueryTableColumn(){ Name = "bankprg", Description = "Banki program azonosító", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "atututv", Description = "Állomány tárolásának útvonala", ColumnType = "string", Length = 30  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "btrkod", Description = "", ColumnType = "string", Length = 3  },
                                	new DynamicQueryTableColumn(){ Name = "jutalek", Description = "-", ColumnType  = "decimal", Length = 5, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "Törölve", ColumnType  = "bool" },
                              },
            		Associations = new List<DynamicQueryTableAssociation>()
            					   {
                                    	new DynamicQueryTableAssociation() { Name = "FK_bankforg_bank", ForeignKeyColumn = "bankkod", ForeignKeyTable = "bankforg", PrimaryKeyColumn = "kod", PrimaryKeyTable = "bank" },
                                   }			
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("bankforg")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bankkod", Description = "Bankszámla belső kódja ->BANK", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "tipus", Description = "Tétel típus (B,K)", ColumnType = "string", Length = 1  },
                                	new DynamicQueryTableColumn(){ Name = "datum", Description = "Könyvelés dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "megnevezes", Description = "Megnevezés", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "brutto", Description = "Bruttó összeg", ColumnType  = "decimal", Length = 13, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "szamlakod", Description = "Tétel megfelelője a SZAMLA állományban", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bizszam", Description = "Bizonylat szám", ColumnType = "string", Length = 20  },
                                	new DynamicQueryTableColumn(){ Name = "pkod", Description = "Partner kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "gep", Description = "Gépszám /int volt/", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "kezelo", Description = "Kezelő kódja", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "oraperc", Description = "Rögzítés időpontja", ColumnType  = "DateTime" },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "", ColumnType  = "bool" },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("beosztas")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "Beosztás megnevezése", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "jogszint", Description = "Jogosultsági szint", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "Törölve", ColumnType  = "bool" },
                              },
            		Associations = new List<DynamicQueryTableAssociation>()
            					   {
                                    	new DynamicQueryTableAssociation() { Name = "FK_felhasznalo_beosztas", ForeignKeyColumn = "beokod", ForeignKeyTable = "felhasznalo", PrimaryKeyColumn = "kod", PrimaryKeyTable = "beosztas" },
                                   }			
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("bevet")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bevetszam", Description = "Bevételezés sorszáma", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "tetelsorszam", Description = "Tétel sorszáma", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "pkod", Description = "Partner kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "szlaszam", Description = "Számlaszám", ColumnType = "string", Length = 20  },
                                	new DynamicQueryTableColumn(){ Name = "szlakod", Description = "Számla belső kódja ->SZAMLA", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "pztbizkod", Description = "Pénztár bizonylat belső kódja->PENZTAR", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bevetdat", Description = "Bevételezés dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "cikkszam", Description = "Cikkszám", ColumnType = "string", Length = 13  },
                                	new DynamicQueryTableColumn(){ Name = "mennyiseg", Description = "Bevételezett mennyiség", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "nagykerar", Description = "Nagyker. ár", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "beszar", Description = "Beszerzési ár", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "fogyar", Description = "Fogyasztói ár", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "afakod", Description = "ÁFA kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "afakulcs", Description = "ÁFA kulcs", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "gyartszam", Description = "Gyártási szám", ColumnType = "string", Length = 20  },
                                	new DynamicQueryTableColumn(){ Name = "gyartev", Description = "Gyártás éve", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "gyartho", Description = "Gyártás hónapja", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "lejardat", Description = "Lejárat dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "rendszam", Description = "Rendelés szám", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bmennyiseg", Description = "Dorottya : bevételezett mennyiség kiszerelési egys.", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "efogyar", Description = "Előző fogyasztói ár", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "enagykerar", Description = "Előző nagyker. ár", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "ebdatum", Description = "Dorottya : utolsó bevételezés dátuma erre a tételre", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "storno", Description = "Sztornírozva", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "kezelo", Description = "Kezelő kódja", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "expedialva", Description = "Bevételezés betöltése eladásba megtörtént", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "gtv", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "tbeszar", Description = "-", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "btip", Description = "Bevételezés típusa (0-Kézi, 1-Gyors készlet, 2-Betöltés rendelésből,3-Elektronikus számlából)", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "rowamenny", Description = "ROWA-ba bevételezett mennyiség", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "ktrkod", Description = "Készlet tranzakció kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bizom", Description = "Bizomyányosi áru jelölése", ColumnType  = "bool" },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("bnotorzs")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "D_KOD", Description = "BNO kód", ColumnType = "string", Length = 5  },
                                	new DynamicQueryTableColumn(){ Name = "D_JEL", Description = "-", ColumnType = "string", Length = 1  },
                                	new DynamicQueryTableColumn(){ Name = "D_NEV", Description = "BNO megnevezése", ColumnType = "string", Length = 150  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "NEM", Description = "", ColumnType = "string", Length = 1  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "KOR_A", Description = "", ColumnType  = "int" },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "KOR_F", Description = "", ColumnType  = "int" },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "ERV_KEZD", Description = "", ColumnType = "string", Length = 8  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "ERV_VEGE", Description = "", ColumnType = "string", Length = 8  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "karbjel", Description = "", ColumnType = "string", Length = 1  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "mezonev", Description = "", ColumnType = "string", Length = 20  },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("cardtipus")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "Típus megnevezés", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "Törölve", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "ktipus", Description = "1=bankkártya,2=egpt.kártya,3=utalvány", ColumnType  = "bool" },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("cikk")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "cikkszam", Description = "cikkszám", ColumnType = "string", Length = 13  },
                                	new DynamicQueryTableColumn(){ Name = "ttt", Description = "TTT kód", ColumnType = "string", Length = 9  },
                                	new DynamicQueryTableColumn(){ Name = "cikkcsop", Description = "cikkcsoport azonosító", ColumnType = "string", Length = 1  },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "rövid név", ColumnType = "string", Length = 60  },
                                	new DynamicQueryTableColumn(){ Name = "kisz", Description = "rövid kiszerelés", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "hh", Description = "honvédelmi jogcímre adható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "kk", Description = "közgyógy jogcímre adható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "uu", Description = "üzemi baleset jogcímre adható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "eu1", Description = "EÜ kiemelt jogcímre adható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "eu2", Description = "EÜ emelt jogcímre adható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "tbszaz", Description = "TB támogatási csoport", ColumnType = "string", Length = 3  },
                                	new DynamicQueryTableColumn(){ Name = "vtsz", Description = "vámtarifaszám", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "afakod", Description = "ÁFA kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "afakulcs", Description = "ÁFA kulcs", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "fogyar", Description = "fogyasztói ár nettó", ColumnType  = "decimal", Length = 16, DecimalLength = 8  },
                                	new DynamicQueryTableColumn(){ Name = "tbalap", Description = "TB által elfogadott ár nettó", ColumnType  = "decimal", Length = 16, DecimalLength = 8  },
                                	new DynamicQueryTableColumn(){ Name = "tammert", Description = "TB támogatás nettó", ColumnType  = "decimal", Length = 16, DecimalLength = 8  },
                                	new DynamicQueryTableColumn(){ Name = "tdij90", Description = "térítési díj EÜ emelt jogcímre nettó", ColumnType  = "decimal", Length = 16, DecimalLength = 8  },
                                	new DynamicQueryTableColumn(){ Name = "tam100", Description = "támogatás EÜ kiemelt jogcímre nettó", ColumnType  = "decimal", Length = 16, DecimalLength = 8  },
                                	new DynamicQueryTableColumn(){ Name = "nagykerar", Description = "nagykereskedelmi ár nettó", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "sbeszar", Description = "súlyozott beszerzési ár nettó", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "rnagykerar", Description = "hatóanyag exp. kód (NICHE_ID) /numeric(10, 2) volt/hatóanyag exp. kód", ColumnType  = "float" },
                                	new DynamicQueryTableColumn(){ Name = "rfogyar", Description = "-", ColumnType  = "decimal", Length = 16, DecimalLength = 8  },
                                	new DynamicQueryTableColumn(){ Name = "beepul", Description = "csomagolás (beépülő mennyiség)", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "gycsomag", Description = "gyüjtő csomag (darab)", ColumnType  = "decimal", Length = 8, DecimalLength = 0  },
                                	new DynamicQueryTableColumn(){ Name = "me", Description = "mennyiségi egység kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "kme", Description = "kiszerelt mennyiségi egység kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "bonthato", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "onmagaban", Description = "magiban önmagában nem adható ki támogatással", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "kiadhato", Description = "Kiadhatóság (I,II)", ColumnType = "string", Length = 2  },
                                	new DynamicQueryTableColumn(){ Name = "hatero", Description = "Hatáserősség (+,++)", ColumnType = "string", Length = 2  },
                                	new DynamicQueryTableColumn(){ Name = "lejardat", Description = "legrégebbi lejárat dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "kabit", Description = "Kábítószer jelzése", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "tilt", Description = "Letiltott cikk", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "megszunt", Description = "Megszűnt cikk", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "mereg", Description = "Méreg", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "hakod", Description = "Helyettesíthetőség kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "rend", Description = "Rendelhetőség (V,SZ, stb.) / Felírható mennyiség", ColumnType = "string", Length = 15  },
                                	new DynamicQueryTableColumn(){ Name = "nykeszlet", Description = "Nyitó készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "keszlet", Description = "Aktuális készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "erkezes", Description = "Érkezett összesen", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "fogyas", Description = "Fogyott összesen", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "efogyas", Description = "Göngyölített fogyás összesen", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "selejt", Description = "Selejt összesen", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "visszaru", Description = "Visszáru összesen", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "tartozas", Description = "Tartozás készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "fuggo", Description = "Függő készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "minimal", Description = "Számitott minimum készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "maximal", Description = "Számitott maximum készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "kmin", Description = "Kézi minimum készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "kmax", Description = "Kézi maximum készlet", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "sadag", Description = "Szokásos napi adag", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "auttilt", Description = "Automata rendelésből letiltva", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "veng", Description = "Csak a vezető engedélyével rendelhető", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "arres", Description = "Cikk egyedi árrés %", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "egyedi", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "utmoddat", Description = "Utolsó módosítás dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "utmodkod", Description = "Utolsó módosítás - kezelő", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "megnevezes", Description = "Hosszú megnevezés", ColumnType = "string", Length = 100  },
                                	new DynamicQueryTableColumn(){ Name = "kiszereles", Description = "Hosszú kiszerelés", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "vizsgalat", Description = "-", ColumnType = "string", Length = 15  },
                                	new DynamicQueryTableColumn(){ Name = "tkszam", Description = "Törzskönyvi szám", ColumnType = "string", Length = 20  },
                                	new DynamicQueryTableColumn(){ Name = "tt", Description = "Törzskönyvi törlés jelzése", ColumnType = "string", Length = 2  },
                                	new DynamicQueryTableColumn(){ Name = "atc", Description = "ATC kód /varchar(7) volt/", ColumnType = "string", Length = 7  },
                                	new DynamicQueryTableColumn(){ Name = "torvbonth", Description = "Bonthatóság", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "isokod", Description = "ISO kód", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "kerkod", Description = "Kereső kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "gyarto", Description = "Gyártó kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "potencia", Description = "Potencia (homeopátia)", ColumnType = "string", Length = 12  },
                                	new DynamicQueryTableColumn(){ Name = "magidij", Description = "Hozzárendelt magi díj osztály", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "kijelol", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "afogyas", Description = "Extra fogyás", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "eafogyas", Description = "Göngyölített extra fogyás", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "megj", Description = "Felhasználó megjegyzése", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "felsz", Description = "Felszívódás kód", ColumnType = "string", Length = 2  },
                                	new DynamicQueryTableColumn(){ Name = "egyedif", Description = "Egyedi forgalmazás jelzése (Dorottya)", ColumnType = "string", Length = 1  },
                                	new DynamicQueryTableColumn(){ Name = "gtvindulo", Description = "DOT", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "tsbeszar", Description = "-", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "gtv", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "gtv100dat", Description = "-", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "termar", Description = "termelői ár", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "termar80", Description = "-", ColumnType  = "decimal", Length = 10, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "nkarres", Description = "Gyógyszer költség hatékonyság (BESOROLAS)", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "kihido", Description = "Kihordási időKihordási idő", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "autlab", Description = "Automatikus laborálás", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "oepkisz", Description = "OEP kiszerelési egysége (váltószám)", ColumnType  = "decimal", Length = 7, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "maxgyogy", Description = "-", ColumnType  = "decimal", Length = 7, DecimalLength = 2  },
                                	new DynamicQueryTableColumn(){ Name = "iparkepz", Description = "Preferált cikk", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "megjqb", Description = "QB megjegyzés (TT dátuma)", ColumnType = "string", Length = 40  },
                                	new DynamicQueryTableColumn(){ Name = "spmagibanem", Description = "Speci magiba nem rakható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "egyeb", Description = "Laktóz,Szacharóz,Alkohol, Rowa, Patika hálózat beállítás, Bontás kézi eladásban", ColumnType = "string", Length = 50  },
                                	new DynamicQueryTableColumn(){ Name = "tarol", Description = "Tárolási hely", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "magibanem", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "mdijujraszam", Description = "Több dózis esetén magi díj újraszámítása", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "mlejar", Description = "Laboráláskor lejárati idő", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "bkeszlet1", Description = "-", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "bkeszlet2", Description = "-", ColumnType  = "decimal", Length = 12, DecimalLength = 4  },
                                	new DynamicQueryTableColumn(){ Name = "kk2", Description = "KGY keretre adható", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "gykhat", Description = "Gyógyszer költség hatékonyság (normatív)", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "oep_ff", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "referencia", Description = "Referencia jelzés", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "ettt", Description = "Régi TTT kód", ColumnType = "string", Length = 9  },
                                	new DynamicQueryTableColumn(){ Name = "autarvalttilt", Description = "Automatikus árváltozásból letiltva", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "infopult", Description = "Info pulton megjelenhet", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "alimed_felvesz", Description = "Alimed törzsbe kerülés dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "qbcikkszam", Description = "QB Cikkszám", ColumnType = "string", Length = 13  },
                                	new DynamicQueryTableColumn(){ Name = "rekesz", Description = "Fellelési hely", ColumnType = "string", Length = 6  },
                                	new DynamicQueryTableColumn(){ Name = "hianycikk", Description = "Hiánycikk", ColumnType  = "bool" },
                              },
            		Associations = new List<DynamicQueryTableAssociation>()
            					   {
                                    	new DynamicQueryTableAssociation() { Name = "FK_arazo_cikk", ForeignKeyColumn = "cikkszam", ForeignKeyTable = "arazo", PrimaryKeyColumn = "cikkszam", PrimaryKeyTable = "cikk" },
                                    	new DynamicQueryTableAssociation() { Name = "FK_bevet_cikk", ForeignKeyColumn = "cikkszam", ForeignKeyTable = "bevet", PrimaryKeyColumn = "cikkszam", PrimaryKeyTable = "cikk" },
                                   }			
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("cikkcsop")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "belső azonosító", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "azonosito", Description = "cikkcsoport azonosító", ColumnType = "string", Length = 1  },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "megnevezés", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "rovidnev", Description = "rövid név", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "hkulcs", Description = "haszonkulcs", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "fix", Description = "program által használt, nem törölhető", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "törölve", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "szin", Description = "-", ColumnType  = "decimal", Length = 18, DecimalLength = 0  },
                                	new DynamicQueryTableColumn(){ Name = "kivalasztva", Description = "-", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "rendez", Description = "cikkcsoport lista rendezettsége", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "nkeszlet", Description = "Nem kezel készletet", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "savosarres", Description = "Sávos árrés tábla használata", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "autarres", Description = "-", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "phalofioksajat", Description = "patikai hálózat fiókja módosíthatja", ColumnType  = "bool" },
                              },
            		Associations = new List<DynamicQueryTableAssociation>()
            					   {
                                    	new DynamicQueryTableAssociation() { Name = "FK_cikk_cikkcsop", ForeignKeyColumn = "cikkcsop", ForeignKeyTable = "cikk", PrimaryKeyColumn = "azonosito", PrimaryKeyTable = "cikkcsop" },
                                   }			
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("feladatok")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "sor", Description = "", ColumnType  = "int" },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "fkod", Description = "", ColumnType  = "int" },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "datum", Description = "", ColumnType  = "DateTime" },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "feladat", Description = "", ColumnType = "string", Length = 250  },
                                	// Documentation is null on this field, please check it
                                	new DynamicQueryTableColumn(){ Name = "st", Description = "", ColumnType  = "bool" },
                              },
        	});	
        	
        	this.Tables.Add(new DynamicQueryTable("felhasznalo")
        	{
            		Columns = new List<DynamicQueryTableColumn>()
            				  {
                                	new DynamicQueryTableColumn(){ Name = "kod", Description = "identity", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "nev", Description = "Felhasználó neve", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "rnev", Description = "Felhasználó rövid neve", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "jelszo", Description = "-", ColumnType = "string", Length = 3  },
                                	new DynamicQueryTableColumn(){ Name = "beokod", Description = "Beosztás kód", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "beosztas", Description = "Beosztás megnevezése", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "szulhely", Description = "Születési hely", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "aneve", Description = "Anyja neve", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "isk", Description = "Iskolai végzettsége", ColumnType = "string", Length = 30  },
                                	new DynamicQueryTableColumn(){ Name = "belepdat", Description = "Belépés dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "kilepdat", Description = "Kilépés dátuma", ColumnType  = "DateTime" },
                                	new DynamicQueryTableColumn(){ Name = "ber", Description = "Bér", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "adoig", Description = "Adóigazolvány száma", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "evesszab", Description = "Éves szabadság", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "igenybevett", Description = "Igénybevett szabadság", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "regikod", Description = "-", ColumnType  = "int" },
                                	new DynamicQueryTableColumn(){ Name = "torolve", Description = "Törölve", ColumnType  = "bool" },
                                	new DynamicQueryTableColumn(){ Name = "munkalapjelszo", Description = "Munkalap jelszó (Qbdesk)", ColumnType = "string", Length = 10  },
                                	new DynamicQueryTableColumn(){ Name = "ujjelszo", Description = "Belépési jelszó kódolva", ColumnType = "string", Length = 60  },
                              },
            		Associations = new List<DynamicQueryTableAssociation>()
            					   {
                                    	new DynamicQueryTableAssociation() { Name = "FK_bankforg_felhasznalo", ForeignKeyColumn = "kezelo", ForeignKeyTable = "bankforg", PrimaryKeyColumn = "kod", PrimaryKeyTable = "felhasznalo" },
                                    	new DynamicQueryTableAssociation() { Name = "FK_bevet_felhasznalo", ForeignKeyColumn = "kezelo", ForeignKeyTable = "bevet", PrimaryKeyColumn = "kod", PrimaryKeyTable = "felhasznalo" },
                                   }			
        	});	
        } // konstruktor end
    }// class end	
} // namespace end
